WOTCStrategyOverhaul/CovertInfiltration

CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActions_MultipleActions.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIEventQueue_MaskedCovertActionListItem.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIEventQueue_MultipleActions.uc
=> Masked Items

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UISSManager_CovertAction.uc
=> Add required soldier class / rank notes

CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape_ResourcesHook.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISSManager_CovertAction.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISS_CostSlot.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISS_CostSlotsContainer.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISS_CovertActionRisks.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIVerticalListItemBase.uc
=> Cost slots on squad select screen

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationMod.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationModTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationModTemplateManager.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationMod_DefaultModifiers.uc
Added some things that might be useful when we start fully connecting the squad select to the CA system.
=> Add functions to calculate squad/unit infiltration

CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc
Dunno if this needs anything else
=> Progress bar for ongoing actions

CovertInfiltration/Config/XComGameCore.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2Ability_InfiltrationAbilitySet.uc
=> Detection radius bug fix

CovertInfiltration/Config/XComUI.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/UIEventQueue_MultipleActions.uc
* Removes the erroneous CAs from the proving grounds queue
* Fixes events using the wrong type of list item
* Simplifies code
Fixes #4
Resolves #52
Supersedes #57
=> Fix a number of UIEventQueue_MultipleAction bugs

CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc
Quick PR to preemptively Complete the tutorial objectives that relate to Covert Actions when the player installs the mod.
Resolves #51
=> Disable CA tutorial

CovertInfiltration/Src/CovertInfiltration/Classes/UISS_InfiltrationPanel.uc
=> remove risks on infiltration missions

CovertInfiltration/Config/XComGameBoard.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/X2CovertMissionInfo_DefaultMissions.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationActions.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc
Branch to create the actual CAs/narrative/reward templates for all eight of our alpha1 Infiltrations. #63
=> Add actions, narratives, and rewards

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape_CovertAction.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActions_MultipleActions.uc
=> CA screen improvements

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertActionExpirationManager.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_PhaseOneActionsSpawner.uc
=> ability for covert infiltrations to expire

.gitmodules, .scripts/build.ps1, .scripts/run.ps1, .scripts/runUnrealEditor.ps1, .vscode/tasks.json, CovertInfiltration.XCOM_sln, CovertInfiltration/CovertInfiltration.x2proj
Opted in for an explicit `clean` option when building downstream mods.
=> [WIP] Add submodules and build scripts

CovertInfiltration/Src/CovertInfiltration/Classes/UIEventQueue_MultipleActions.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc
Closes #65. Depends on https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/396.
=> Covert actions in event queue fixes

CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UIDropWeaponUpgradeButton.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_SSManageEquipment.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_WeaponUpgrade.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIListner_SSManageEquipment.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc
=> Enabling lock-n-load from start

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_CovertActionCompleted.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
=> Rework soldier will adjustments after returning from CovertAction

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISkyrangerExfiltrate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_SquadPickupPoint.uc
=> Add ability to cancel CAs

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/CI_UIStrategyMapItem_CovertAction.uc
=> nameplates for CA map entities

CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc
=> Fixed disappearing infiltration status

CovertInfiltration/Config/XComInfiltration.ini
=> overinfil bonuses wired up

CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/UIBetterSitRepDetails.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIBetterSitRepDetails_Row.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_SitRepInformation.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2SitRep_InfiltrationSitRepEffects.uc
=> Improve sitrep details screen

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/CI_UIStrategyMapItem_CovertAction.uc
=> CA nameplate fixes

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UIMission_Infiltrated.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2CovertMissionInfoTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2CovertMissionInfo_DefaultMissions.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2OverInfiltrationBonusTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultOverInfiltrationBonuses.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
=> Better overinfil UI

CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CIReinforcementsManager.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertActionExpirationManager.uc
=> [WIP] Better RNFs SitRep

CovertInfiltration/Src/CovertInfiltration/Classes/CI_UIStrategyMapItem_CovertAction.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
=> Overinfiltration Nameplates

CovertInfiltration/Config/XComInfiltration.ini
Closes #178. Commits in bridges:
* WOTCStrategyOverhaul/CIBridge_SMG@2f6a945daf44d59f7107b3271c1f1cf2f4a8efcf
* WOTCStrategyOverhaul/CIBridge_LW2Secondary@ce071d83708f26f72d874dcf81902983a6679b4e
=> Removed mod infil and deterrence data from config

CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc
=> remove soldiers from infiltrations if the action has expired

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_PhaseOneActionsSpawner.uc
=> Miscellaneous fixes for #168 and #170

CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc
=> force no ca nag on the geoscape ui during first month

CovertInfiltration.XCOM_sln, CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Assault.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2CovertInfiltrationTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2OverInfiltrationBonusTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultOverInfiltrationBonuses.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
Closes #215 
TODO:
(1) SitRep incompatibility
(2) SitRep requirements by mission types
=> Sitreps on assault missions

CovertInfiltration/Config/XComGameData.ini
=> added exclusive sitreps to config file

CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_StaffSlots_Infiltration.uc
=> allow wounded sparks to embark on infiltrations

CovertInfiltration/Config/XComGameBoard.ini, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc
Also made a little balance change because it's causing a few issues with "[reward1], [reward2]" turning into ", Facility Lead"
=> Fix activities missing localization

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape_CovertAction.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Assault.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_CovertAction.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Activity.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChain.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertInfiltrationInfo.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
=> New activity event notice

CovertInfiltration/Config/XComGameData.ini
=> Improve chosen spawning chance

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UISS_InfiltrationReadout.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
=> Bondmate ca duration bonus

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc
Closes #257 
Closes #261 
Closes #282 
Closes #278 
Closes #277 
Closes #281 (together with 8cb3595fa18f0e658570915be095c5fd40c2968e)
=> Full Localization Cleanup

CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Config/XComStrategyTuning.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/UIFacility_AcademySlot_CI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2AcademyTrainingRankUnlockTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationUnlocks.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_HeadquartersProjectTrainAcademy.uc
=> Flexible gts

CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Assault.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
Closes #273 
TODO: CHL event for `UIResistanceReport` to prevent showing councilguy before the intro cinematic
=> Better councilman reveal

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc
Closes #291 except for the supply raid issue which is as of yet undecided
=> Enable gather intel and gather supplies

CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
=> Diversify sound effects for infiltrations on geoscape

CovertInfiltration/Config/XComGame.ini, CovertInfiltration/Config/XComStrategyTuning.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc
Closes #328 
As discussed in that issue, medikit/flash/smoke costs are being set to 15/13/10.
=> Rebalance supply cost of starting items

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertInfiltrationInfo.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
=> Kill XP adjustment system

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChainSpawner.uc
Currently set to Rescue Engineer as per #330
=> Add config option to hardcode a chain as the first of the campaign

CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_SitReps.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertInfiltrationInfo.uc
=> corrected the intended functionality of Comms Jamming

CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc
=> Add a bit of Intel to the POI spawning reward

CovertInfiltration/Config/XComEncounterLists.ini, CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2SitRepEffect_ModifyEncounter.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2SitRep_InfiltrationSitRepEffects.uc
Closes #386 
Several TODOs left in code + testing
=> Sitrep modify encounter

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Config/XComUI.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape_FactionHeader.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_SquadSelect.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIMission_Infiltrated.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISSManager_CovertAction.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_InfiltrationTutorial.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationFacilityUpgrades.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertInfiltrationInfo.uc
=> Redo tutorial localization and popup locations

CovertInfiltration/Src/CovertInfiltration/Classes/X2Ability_SitRepAbilitySet_CI.uc
=> changed the color of sitrep granted passive abilities

CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChain.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChainSpawner.uc
=> Rework dark event selection and counter chain spawning

CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertInfiltrationInfo.uc
=> Upgrade items for soldiers that are returning from an infiltration

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc
=> Add "chain completed/progressed/failed" text to mission debrief

CovertInfiltration/Config/XComGameBoard.ini
=> added duration times to covert actions that were missing them

CovertInfiltration/Config/XComGameBoard.ini, CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Config/XComMissionSources.ini, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Assault.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc
=> Rearrange personnel and dark event chains

CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/Config/XComUI.ini, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationMod.uc
=> Add infil and deterrence stats to the loadout menu

CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape_Risk.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISS_InfiltrationReadout.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISS_Risk.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActionRiskDescriptionSet.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActionRiskDescriptionTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActionRiskDescriptionTemplateManager.uc
=> Risk descriptions

CovertInfiltration/Config/XComUI.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UIAlert_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertInfiltrationInfo.uc
Closes #369 
@cannonfodder1 @ChrisTheThinMint  I need text and the image
=> Crew overflow popup

CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc
=> Rework GetUnitDetails function to fix UNITNOTFOUND bug

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2ComplicationTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultComplications.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChain.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Complication.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Complication_RewardInterception.uc
=> Fix complications not properly intercepting intel rewards

CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc
Made it return something (I hope)
Closes #463
=> #463: SoldierInfiltrationToStrategyUpgradeGear no return

CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Assault.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
Changes the backend so POIs are attached to the mission on spawning, not on completion
CC #325
=> POI attachment changes

CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UIDags.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIInfiltrationDetails.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIInfiltrationDetails_Milestone.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIMission_Infiltrated.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
=> Infiltration details screen

CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Assault.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Activity_Assault.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Activity_Infiltration.uc
=> Cleanup missionsites when activities expire

CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UITutorialBoxLarge.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_InfiltrationTutorial.uc
=> Better tutorial UI

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc
=> Prevent random negative and positive sitreps from spawning on retaliations

CovertInfiltration/Config/XComGameBoard.ini, CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Config/XComMissionSources.ini, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityChainTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Assault.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_CovertAction.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationModTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultComplications.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChain.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChainSpawner.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
CC #445 
Closes #439 
Closes #322 
Closes #480
=> Activity system overhaul to create semi-randomized chains

CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc
=> Show an activity's place in its chain on the covert ops list

CovertInfiltration/Config/XComMissionSources.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
=> Fix quest items when using chain proxy reward

CovertInfiltration/Content/GeoscapeMesh_CI.upk, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc
=> Use datatap instead of radio tower as a geoscape marker for intel missions

CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc
=> Add delay dark event reward on the first mission of the CDE chain

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2RetalPlacementModifierSet.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2RetalPlacementModifierTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2RetalPlacementModifierTemplateManager.uc
=> Retal placement

CovertInfiltration/Config/XComGameData.ini, CovertInfiltration/Config/XComMissionSources.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc
=> Give rewards for completing secondary objectives of Informant Assault missions

CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChainSpawner.uc
=> Spawn the correct amount of counter chains for the number of pending dark events

CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultComplications.uc
=> Cleanup the chosen surviellance complication when the chosen are defeated

CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc
=> Restrict facility lead chain spawning to only contacted regions

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
=> Don't check for irrelevant items that are equipped to inflexible slots

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Config/XComMissionSources.ini, CovertInfiltration/Localization/CovertInfiltration.int, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc
=> Add hack/recover missions to Counter Dark Event stage 2

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChain.uc
Closes #606. See https://discord.com/channels/578606792448409610/656035944058847232/812996856958550067 for current problems
=> Make selected mission types (in particular CDE A1) more evenly distributed

CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/UIStrategyPolicyAdjuster.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc
Closes #620
This is completed and fully tested (I hope) but the events still need to be formally submitted to the CHL
=> Scrollable card columns

CovertInfiltration/Config/XComGameBoard.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationActions.uc
=> Prevent the tech rush covert action from spawning

CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc
Closes #586 
After testing this, I am now a retired XCOM 2 achievement hunter
=> Fix squadsize achievement improperly triggering

CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc
Discord ref: https://discord.com/channels/578606792448409610/639765305345835009/856054058641391626
~~TODO: Test~~ Done
=> Prevent simultanous faction soldier chains

CovertInfiltration/Config/XComMissionSources.ini, CovertInfiltration/CovertInfiltration.x2proj, CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Activity_Assault_Informant.uc
=> Fix the primary VIP on the ResOps mission types

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationMod.uc
=> Add framework to edit existing infil templates and allow non-Firaxis DLC to be detected

CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
=> Limit current infil % to the max allowed

CovertInfiltration/Config/XComInfiltration.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultComplications.uc
=> Fix reward interception spawning on missions with no resource rewards

CovertInfiltration/Config/XComGameCore.ini, CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc
=> Increased the contents of each crate in supply extraction by 20%

CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape_Risk.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISS_InfiltrationReadout.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UISS_Risk.uc, CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc
=> Better (long) risk description UI

CovertInfiltration/Localization/XComGame.int, CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationUnlocks.uc
=> Lock the second infil size GTS upgrade behind the first

CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
=> Reroll chosen on assault missions after another mission

CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc
=> Implemented delegate override for `SparkStaffSlot`

CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2RetalPlacementModifierSet.uc, CovertInfiltration/Src/CovertInfiltration/Classes/X2RetalPlacementModifierTemplate.uc
Fixes compiling the package for some people
=> Move `IsRelevantToRegionFn` to `CI_DataStructures`

CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
Implementation for caching mission difficulty when the chain stage starts. Proposal for #702 .
Made it affect Assaults too, as there is technically a window for the difficulty to change on those as well.
=> Cache mission difficulty

CovertInfiltration/Localization/FRA/BetterSecondWaveSupport.fra, CovertInfiltration/Localization/FRA/CovertInfiltration.fra, CovertInfiltration/Localization/FRA/XcomGame.fra
Add a french translation to Covert Infiltration
=> French translation
